spring.application.name=numi-ai-api

server.port=8080

spring.profiles.active80=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.flyway.enabled=false

spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.3

app.jwt.secret=dev-secret-key-minimo-256-bits-para-funcionar-corretamente-aqui
app.jwt.expiration-ms=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.com.numiAI=DEBUG